default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  host: localhost

development:
  <<: *default
  database: ramjitest_development_environment

test:
  <<: *default
  database: ramjitest_test_environment

production:
  adapter: postgresql
  encoding: unicode
  database: ramjitest_production_environment
  username: postgres
  password: postgres
  host: localhost